name: CI/CD

on:
  push:

jobs:
  gitflow-enforcer:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'develop' || github.base_ref == 'production' && github.head_ref != 'main'
        run: |
          echo "ERROR: You can only merge to main from dev and to production from main"
          exit 1

  lint:
    name: Lint shell scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

  format:
    name: Format code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./deploy ./scripts ./lambdas"
          version: "22.8.0"

  test_build-stac:
    name: Test lambdas/build-stac
    uses: ./.github/workflows/test_docker_lambda.yml
    with:
      path_to_lambda: lambdas/build-stac

  test_data-transfer:
    name: Test lambdas/data-transfer
    uses: ./.github/workflows/test_python_lambda.yml
    with:
      path_to_lambda: lambdas/data-transfer
