on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy to dev environment
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_env: dev
    secrets:
      cognito_app_secret: ${{ secrets.cognito_app_secret }}
      aws_access_key_id: ${{ secrets.aws_access_key_id }}
      aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
      stac_ingestor_url: ${{ secrets.stac_ingestor_url }}
      external_role_arn: ${{ secrets.external_role_arn }}
      vector_secret_name: ${{ secrets.vector_secret_name }}
      vector_vpc_id: ${{ secrets.vector_vpc_id }}
      vector_security_group: ${{ secrets.vector_security_group }}
      oidc_role_arn: ${{ secrets.oidc_role_arn }}

