on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to staging environment
    uses: ./.github/workflows/deploy_oidc.yml
    with:
      deploy_env: staging
    secrets:
      oidc_role_arn: ${{ secrets.oidc_role_arn }}
