on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      cognito_app_secret:
        required: true
      stac_ingestor_url:
        required: true
      external_role_arn:
        required: true
      vector_secret_name:
        required: true
      vector_vpc_id:
        required: true
      vector_security_group:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python, caching dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Manually install requirements.txt
        run: pip install -r deploy/requirements.txt
      
      - name: Install node and related deps
        uses: actions/setup-node@v3
        with:
          node-version: 17.3.0

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: deploy
        run: cd deploy && cdk deploy --all --require-approval never
        env:
          ENV: ${{ inputs.deploy_env }}
          COGNITO_APP_SECRET: ${{ secrets.COGNITO_APP_SECRET }}
          STAC_INGESTOR_URL: ${{ secrets.STAC_INGESTOR_URL }}
          APP_NAME: "veda-data-pipelines"
          EXTERNAL_ROLE_ARN: ${{ secrets.EXTERNAL_ROLE_ARN }}
          VECTOR_SECRET_NAME: ${{ secrets.VECTOR_SECRET_NAME }}
          VECTOR_VPC_ID: ${{ secrets.VECTOR_VPC_ID }}
          VECTOR_SECURITY_GROUP: ${{ secrets.VECTOR_SECURITY_GROUP }}
