on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Deploy environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging

jobs:
  deploy:
    uses: ./.github/workflows/deploy_oidc.yml
    with:
      deploy_env: ${{ inputs.deploy_env }}
    secrets:
      oidc_role_arn: ${{ secrets.oidc_role_arn }}
