name: Validate Datasets

# on .json PR to /data/datasets folder
on: 
  push:
    secrets:
      stac_ingestor_url:
        required: true
      client_id:
        required: true
      client_secret:
        required: true
      cognito_domain:
        required: true
      scope:
        required: true
    paths:
      - 'data/datasets/**'

# send pushed file as body to (API)/datasets/validate using secret credentials
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Filter for dataset files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'main'
          list-files: shell
          filters: |
            dataset:
              - added|modified: 'data/datasets/*.json'
      - name: Validate datasets using API
        if: steps.filter.outputs.dataset == 'true'
        env:
          STAC_INGESTOR_URL: ${{ secrets.STAC_INGESTOR_URL }}
        shell: bash
        run: |
          curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&scope=${{ secrets.scope }}" \
            -u "${{ secrets.client_id }}:${{ secrets.client_secret }}" \
            "${{ secrets.cognito_domain }}/oauth2/token" > token.txt
          error_flag=0
          for file in ${{ steps.filter.outputs.dataset_files }}
          do
            echo "Validating $file"
            token=$(cat token.txt | jq -r '.access_token')
            # if 200 not returned, set outputs to print code and message
            http_response=$(curl -N -s -o response.txt -w "%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $token" \
              -H "accept: application/json"\
              -d @$file \
              "$STAC_INGESTOR_URL/dataset/validate")
            if [ $http_response -ne 200 ]; then
              echo "Error validating $file"
              echo "HTTP Response: $http_response"
              echo "Response Body: $(cat response.txt)"
              error_flag=1
            fi
          done
          if [ $error_flag -eq 1 ]; then
            exit 1
          fi